# General settings
name: 'graph-tf-model'      # Warning: 'debug' and 'test' are reserved name that have a special behavior


forward_visualization: False
sample_visualization: False
vis_number: 5


wandb: 'disabled'             # online | offline | disabled
gpus: [0, ]                     # Multi-gpu is not implemented on this branch


resume: null            # If resume, path to ckpt file from outputs directory in main directory
test_only: null         # Use absolute path

check_val_every_n_epochs: 5000
sample_every_val: 1
val_check_interval: null
samples_to_generate: 300       # We advise to set it to 2 x batch_size maximum
samples_to_save: 20
chains_to_save: 1
log_every_steps: 50
number_chain_steps: 50        # Number of frames in each gif

final_model_samples_to_generate: 300
final_model_samples_to_save: 20
final_model_chains_to_save: 20
#final_model_samples_to_generate: 3
#final_model_samples_to_save: 2
#final_model_chains_to_save: 1

evaluate_all_checkpoints: False

